### ISSUE TITLE
Icon request: fab fa-amazon-music

### ISSUE THREAD

**Issue by kylewelsby** [FortAwesome/Font-Awesome#13403]
Online streaming services are heating up and it would be ideal to have the Icons to help promote artists on different platforms equally.

Here we're requesting **Amazon Music** https://amazon.com/digitalmusic

![amazon 91e18ff3](https://user-images.githubusercontent.com/110469/41812102-839a2768-7714-11e8-9e0c-1aaf365b01a3.png)

---

Current status of music streaming services(at time of request):
* [x] [fab fa-spotify](https://fontawesome.com/icons/spotify)
* [x] [fab fa-itunes](https://fontawesome.com/icons/itunes)
* [ ] [fab fa-apple-music](https://fontawesome.com/icons/apple-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/10500)
* [ ] [fab fa-youtube-music](https://fontawesome.com/icons/youtube-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/13402)
* [ ] [fab fa-deezer](https://fontawesome.com/icons/deezer) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/2802)
* [ ] [fab fa-tidal](https://fontawesome.com/icons/tidal) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/8850)
* [ ] [fab fa-youtube-music](https://fontawesome.com/icons/youtube-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/13402)
* [ ] [fab fa-yandex-music](https://fontawesome.com/icons/yandex-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/16118)

**Comment by havokmega** [comment]
I literally just now signed up for github to be able to upvote a request for a Beatport icon. It's been requested for years and I think that would be better to add before revising icons that already exist. I run a record label and my shop has custom icons for Spotify, iTunes, Youtube, Amazon Music, and Google Play. But every DJ I've known in the last 20 years gets their tracks from Beatport. So my shop has some lame musical notes in place of Beatport instead of their hip headphone logo/icon. What do you think?
![no beatport icon](https://user-images.githubusercontent.com/54377015/63466687-a3549780-c418-11e9-97c5-e8a9e3e7adc2.png)

**Comment by sanek4life** [comment]
+1

**Comment by jminguely** [comment]
+1

**Comment by brycebreeds** [comment]
+1

**Comment by Pythogen7** [comment]
+1

**Comment by sensibleworld** [comment]
So... our backlog of brand requests has reached a point where even we can't pretend we're keeping up. Some of these issues were opened before I had gray hair. And I've had gray hair for a LONG time. On top of that, treating requests as issues has always made it way too hard to see the forest for the trees.

To fix this, we are now managing all brand requests in **GitHub Discussions**. No more +1s or thumbs-ups needed. There's an upvote system built-in.

We are closing existing brand requests as part of this transition, but **we are not saying no** to your request.

**If this brand request is still relevant for you, please re-open it in Discussions** (and feel free to include a link back to this issue):
-> https://github.com/FortAwesome/Font-Awesome/discussions/new?category=brand-requests

And listen. We know this is annoying. If you need to vent, here are some pre-written responses you can use when opening the new discussion:

* Cool cool cool. No worry at all. I love re-requesting a brand that's redesigned three times while this issue was open.
* If an issue closes after seven years and nobody responds, did it ever really exist?
* I see you have chosen violence today. Re-opening per instructions.
* What's next? I have to file a TPS report, too?
* I am filled with the fury of a thousand suns. Why do I have to re-open the discussion? Couldn't you have just bulk converted all of the issues to discussions? What? You couldn't? What do you mean Github removed that feature earlier this year? You'd have to manually click the "convert to discussion" button on thousands of issues, while also ensuring it gets added to the correct category? That's a bunch of bull-phooey.
* No biggie.
