### ISSUE TITLE
Icon request: fab fa-youtube-music

### ISSUE THREAD

**Issue by kylewelsby** [FortAwesome/Font-Awesome#13402]
Online streaming services are heating up and it would be ideal to have the Icons to help promote artists on different platforms equally.

Here we're requesting **YouTube Music** https://music.youtube.com

[I have found the logo assets here](http://logos.wikia.com/wiki/YouTube_Music)

![youtube_music_icon](https://user-images.githubusercontent.com/110469/41812098-71d75190-7714-11e8-81e4-ac4cd3ad111f.png)

---

Current status of music streaming services(at time of request):
* [x] [fab fa-spotify](https://fontawesome.com/icons/spotify)
* [x] [fab fa-itunes](https://fontawesome.com/icons/itunes)
* [ ] [fab fa-apple-music](https://fontawesome.com/icons/apple-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/10500)
* [ ] [fab fa-amazon-music](https://fontawesome.com/icons/amazon-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/13403)
* [x] [fab fa-deezer](https://fontawesome.com/icons/deezer) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/2802)
* [ ] [fab fa-tidal](https://fontawesome.com/icons/tidal) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/8850)
* [ ] [fab fa-youtube-music](https://fontawesome.com/icons/youtube-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/13402)
* [ ] [fab fa-yandex-music](https://fontawesome.com/icons/yandex-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/16118)

**Comment by kaassouffle** [comment]
Maybe also add Tidal ?

**Comment by heismauri** [comment]
+1

**Comment by mattbrett** [comment]
+1

And it looks like the icon has been updated since the original request was made.

![youtube-music-app-icon-red-white](https://user-images.githubusercontent.com/868109/63057127-5d3e8780-be9e-11e9-9488-bf280a5ff1ed.png)

**Comment by havokmega** [comment]
I literally just now signed up for github to be able to upvote a request for a Beatport icon. It's been requested for years and I think that would be better to add before revising icons that already exist. I run a record label and my shop has custom icons for Spotify, iTunes, Youtube, Amazon Music, and Google Play. But every DJ I've known in the last 20 years gets their tracks from Beatport. So my shop has some lame musical notes in place of Beatport instead of their hip headphone logo/icon. What do you think? 
![no beatport icon](https://user-images.githubusercontent.com/54377015/63466745-c3845680-c418-11e9-8d15-7990c91a1e54.png)

**Comment by addftoxic** [comment]
+1 YouTube Music seems to pushing forward fast

**Comment by sanek4life** [comment]
+1

**Comment by maxjutras** [comment]
+1 for youtube music

**Comment by jminguely** [comment]
+1

**Comment by KendallDoesCoding** [comment]
+1

**Comment by iandeveseleer** [comment]
+1

**Comment by KendallDoesCoding** [comment]
Any update on this?

**Comment by RaffaeleBianc0** [comment]
+1

**Comment by short443** [comment]
+1

**Comment by blokovi** [comment]
+1

**Comment by BAProductions** [comment]
+1

**Comment by mjkzy** [comment]
+1

**Comment by pixiekat** [comment]
+1! Yes, please. I don't have a Youtube channel but I'd love to link to my yt-music profile.

**Comment by leoherzog** [comment]
It's backed into being one of the most popular podcast players in the world.

https://www.youtube.com/howyoutubeworks/resources/brand-resources/#podcast-badging

https://partnermarketinghub.withgoogle.com/brands/youtube-music/visual-identity/

https://partnermarketinghub.withgoogle.com/brands/youtube-music/visual-identity/visual-identity/YouTube-Music-app-icon/

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Standard_product_icon" enable-background="new 0 0 24 24" version="1.1" viewBox="0 0 24 24" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <path d="m12 2c-5.52 0-10 4.48-10 10s4.48 10 10 10 10-4.48 10-10-4.48-10-10-10zm0 15.92c-3.27 0-5.92-2.65-5.92-5.92s2.65-5.92 5.92-5.92 5.92 2.65 5.92 5.92-2.65 5.92-5.92 5.92z" clip-path="url(#Bounding_Box_1_)"/>
  <path d="m12 6.81c-2.86 0-5.19 2.33-5.19 5.19s2.33 5.19 5.19 5.19 5.19-2.33 5.19-5.19-2.33-5.19-5.19-5.19zm-1.93 8.14v-5.9l5.11 2.95-5.11 2.95z" clip-path="url(#Bounding_Box_1_)"/>
</svg>
```

**Comment by sensibleworld** [comment]
So... our backlog of brand requests has reached a point where even we can't pretend we're keeping up. Some of these issues were opened before I had gray hair. And I've had gray hair for a LONG time. On top of that, treating requests as issues has always made it way too hard to see the forest for the trees.

To fix this, we are now managing all brand requests in **GitHub Discussions**. No more +1s or thumbs-ups needed. There's an upvote system built-in.

We are closing existing brand requests as part of this transition, but **we are not saying no** to your request.

**If this brand request is still relevant for you, please re-open it in Discussions** (and feel free to include a link back to this issue):
-> https://github.com/FortAwesome/Font-Awesome/discussions/new?category=brand-requests

And listen. We know this is annoying. If you need to vent, here are some pre-written responses you can use when opening the new discussion:

* Cool cool cool. No worry at all. I love re-requesting a brand that's redesigned three times while this issue was open.
* If an issue closes after seven years and nobody responds, did it ever really exist?
* I see you have chosen violence today. Re-opening per instructions.
* What's next? I have to file a TPS report, too?
* I am filled with the fury of a thousand suns. Why do I have to re-open the discussion? Couldn't you have just bulk converted all of the issues to discussions? What? You couldn't? What do you mean Github removed that feature earlier this year? You'd have to manually click the "convert to discussion" button on thousands of issues, while also ensuring it gets added to the correct category? That's a bunch of bull-phooey.
* No biggie.
