### ISSUE TITLE
Icon request: fab fa-yandex-music

### ISSUE THREAD

**Issue by universewrld** [FortAwesome/Font-Awesome#16118]
![xEp4jatgWiafWtW4bTOJ_s4K9R4](https://user-images.githubusercontent.com/3662519/73172328-cdbb2700-4113-11ea-8ec8-903ed3e307fb.png) ![6T3x5i8L7BBhYRO3fYz41q85OOU](https://user-images.githubusercontent.com/3662519/73172332-d14eae00-4113-11ea-97ed-9b606db2c15c.png) ![UTOUjerVecAlNoAyC0Zik9byYLk](https://user-images.githubusercontent.com/3662519/73172335-d3b10800-4113-11ea-8efb-2be2664dbeac.png)
[https://music.yandex.com](https://music.yandex.com)

**Official SVG icons:**
1) [https://cache-mskm902.cdn.yandex.net/download.cdn.yandex.net/from/yandex.ru/support/ru/music/files/icon_main.svg](https://cache-mskm902.cdn.yandex.net/download.cdn.yandex.net/from/yandex.ru/support/ru/music/files/icon_main.svg)
2) [https://download.cdn.yandex.net/from/yandex.ru/support/ru/music/files/icon_main.svg](https://download.cdn.yandex.net/from/yandex.ru/support/ru/music/files/icon_main.svg)
3) [https://download.cdn.yandex.net/from/yandex.ru/support/ru/music/files/icon_add.svg](https://download.cdn.yandex.net/from/yandex.ru/support/ru/music/files/icon_add.svg)

 [https://yandex.ru/support/music/performers-and-copyright-holders/icon.html](https://yandex.ru/support/music/performers-and-copyright-holders/icon.html)

Yandex Music is a music streaming service developed by Yandex. Users select musical compositions, albums, collections of musical tracks to stream to their device on demand and receive personalized recommendations. The service is also available as a mobile app with versions compatible with iOS, Android. Service is available in Russia, Belarus, Kyrgyzstan, Kazakhstan, Azerbaijan, Armenia, Georgia, Tajikistan, Moldova, Israel. Subscription can only be paid from supported countries above, but the service is then available in all other countries.

As of October 2017, over 40 million music tracks were available on Yandex Music. About 20 million people use the service at least once a month

In January 2019, Yandex Music signed a streaming contract with spotify uk 
Source: [https://en.wikipedia.org/wiki/Yandex_Music](https://en.wikipedia.org/wiki/Yandex_Music)

Current status of music streaming services(at time of request):
 
* [x]  [fab fa-spotify](https://fontawesome.com/icons/spotify)
* [x]  [fab fa-itunes](https://fontawesome.com/icons/itunes)
* [ ]  [fab fa-apple-music](https://fontawesome.com/icons/apple-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/10500)
* [ ]  [fab fa-amazon-music](https://fontawesome.com/icons/amazon-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/13403)
* [x]  [fab fa-deezer](https://fontawesome.com/icons/deezer) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/2802)
* [ ]  [fab fa-tidal](https://fontawesome.com/icons/tidal) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/8850)
* [ ]  [fab fa-youtube-music](https://fontawesome.com/icons/youtube-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/13402)
* [ ]  [fab fa-yandex-music](https://fontawesome.com/icons/yandex-music) | [open issue](https://github.com/FortAwesome/Font-Awesome/issues/16118)

**Comment by sanek4life** [comment]
@tagliala Currently, Yandex.Music is the most popular streaming service in Russia and the CIS (former USSR countries). 

I hope that in the next releases we will see the icons of the main music streaming services! 😊🎵
 #2802 #10500 #13403 #8850 #13402 

These icons are very important for music websites! Please add them!

**Comment by sanek4life** [comment]
@kylewelsby I updated the list of music streaming services! Check it out!

**Comment by sensibleworld** [comment]
So... our backlog of brand requests has reached a point where even we can't pretend we're keeping up. Some of these issues were opened before I had gray hair. And I've had gray hair for a LONG time. On top of that, treating requests as issues has always made it way too hard to see the forest for the trees.

To fix this, we are now managing all brand requests in **GitHub Discussions**. No more +1s or thumbs-ups needed. There's an upvote system built-in.

We are closing existing brand requests as part of this transition, but **we are not saying no** to your request.

**If this brand request is still relevant for you, please re-open it in Discussions** (and feel free to include a link back to this issue):
-> https://github.com/FortAwesome/Font-Awesome/discussions/new?category=brand-requests

And listen. We know this is annoying. If you need to vent, here are some pre-written responses you can use when opening the new discussion:

* Cool cool cool. No worry at all. I love re-requesting a brand that's redesigned three times while this issue was open.
* If an issue closes after seven years and nobody responds, did it ever really exist?
* I see you have chosen violence today. Re-opening per instructions.
* What's next? I have to file a TPS report, too?
* I am filled with the fury of a thousand suns. Why do I have to re-open the discussion? Couldn't you have just bulk converted all of the issues to discussions? What? You couldn't? What do you mean Github removed that feature earlier this year? You'd have to manually click the "convert to discussion" button on thousands of issues, while also ensuring it gets added to the correct category? That's a bunch of bull-phooey.
* No biggie.
