### ISSUE TITLE
Icon request: subtask

### ISSUE THREAD

**Issue by srehmanali** [FortAwesome/Font-Awesome#16538]
**What can it be used for?**
This icon is very useful in project management applications where developer can simply place the icon rather typing the word. 

**Example image (optional)**
![2020-04-28_0655](https://user-images.githubusercontent.com/20923838/80442087-4dc47900-891d-11ea-8607-096f13915b8d.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
Single
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by darksnake747** [comment]
100% agree with this request. I actually spent 20 minutes today searching and searching in the library for this exact icon because I just refused to accept it wasn't in there already - especially since they have similar icons like folder-tree. Not saying this negatively toward Font Awesome (love you guys!); just explaining where I am coming from. I finally Googled it and found this issue.

I would love to see this one added. Thank you so much!

**Comment by srehmanali** [comment]
Hi, I would love to hear your response on this.

**Comment by tagliala** [comment]
@srehmanali you may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

**Comment by darksnake747** [comment]
Thanks for the reply on this @tagliala! @srehmanali, I am right there with you on this one. Though, I have looked at the requests and this one is no where near the top voted. Unfortunately, the cost to sponsor an icon or full set is pretty hefty - NOT for what you get though; but for "the average Joe" such as myself, it is too much to pay for right now.

That said, all we can really do is find an alternative for the icons we need until they get around to these (if they do). I have no doubt that if they did make these icons, they would be outstanding and most likely better than any alternative we may find; but, they definitely have a full plate.

I guess another option is to try and get this icon request "out there" for more people to support... but, I'm no "influencer"... so my reach is underwhelming to say the least.

~Cheers~

**Comment by darksnake747** [comment]
@srehmanali I also wonder if we can change the title of this to include other keywords like subitem, sub-item, child-tasks, child-item... etc. Cause searching the issues is a little tricky. Even me knowing about this one I ended up finding the #11015 instead of this one. Just a thought...

**Comment by aethior** [comment]
Hi @srehmanali,

This icon has been added in v6.0.0-BETA3.
Check https://fontawesome.com/icons/diagram-subtask

Regards.

cc/ @tagliala
