### ISSUE TITLE
Brand request: Zalo

### ISSUE THREAD

**Issue by quangdd98** [FortAwesome/Font-Awesome#19588]
### Description

This is a popular social media in Vietnam, which used in working, chating with family, etc. 
I wish you can add Zalo icon in a huge icon family of Font-Awesome.

To make the job simpler, I attached the SVG file of the Zalo logo, you can refer to the official logo on the homepage [Zalo.me](https://zalo.me). Thank you!

![zalo logo](https://github.com/FortAwesome/Font-Awesome/assets/26488181/1997423e-d9e2-475d-b2e2-ac839a0ad633)

### Official website

https://zalo.me

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)
```[tasklist]
### Tasks
- [x] updated the square Zalo icon with less rounded corners
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17300, but since there is just un upvote there, let's use this one which is much better

**Comment by tdnphuong** [comment]
I hope this gets done soon,
I have a lot of trouble when I want to insert Zalo icon

**Comment by luuhlong** [comment]
Waiting for update

**Comment by damnedbrain** [comment]
same

**Comment by ghost** [comment]
upvote

**Comment by GuaBaiChi** [comment]
upvote

**Comment by quangdd98** [comment]
@tagliala Can you tell me the time I should wait for publication?

**Comment by tagliala** [comment]
Hi @quangdd98, please take a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

**Comment by Tuanpluss02** [comment]
Upvote

**Comment by h2im** [comment]
+1

**Comment by dokimkhanh** [comment]
Same

**Comment by GenzPN** [comment]
+1 Upvote

**Comment by selltool** [comment]
+1 Upvote

**Comment by ndbac** [comment]
+1 upvote

**Comment by vietthang197** [comment]
+1 upvote

**Comment by tagliala** [comment]
Hello, thanks for your interest in this request!

Just a friendly reminder that upvotes should be given through reactions and not by commenting.

Commenting will send notifications to everyone involved in the conversation, which can be quite distracting.

Thank you for your understanding!

**Comment by ghost** [comment]
> Hello, thanks for your interest in this request!
> 
> Just a friendly reminder that upvotes should be given through reactions and not by commenting.
> 
> Commenting will send notifications to everyone involved in the conversation, which can be quite distracting.
> 
> Thank you for your understanding!

Dear sir, we need the Zalo icon.

**Comment by kenji68** [comment]
Omg i like it. thanks for share!!!

**Comment by nguyenthao1988** [comment]
Good job!

**Comment by nguyenthao1988** [comment]
Please help us.

**Comment by datgausaigon** [comment]
@nguyenthao1988 Nếu được bạn cho xin thêm giúp Logo Zalo hình vuông tiêu chuẩn vào bộ nữa bạn. Dân Dev thật khó khăn khi tìm bộ nguồn ảnh vector gốc của Zalo. Nếu được thì rất mong các bạn bên Zalo nên công bố link download bộ Logo đầy đủ của Zalo để anh em Dev thuận tiện hơn.

![Zalo__Logo-1](https://github.com/FortAwesome/Font-Awesome/assets/2121900/237e612b-a8a1-4b58-8a2a-0fce05be9cd2)

**Comment by quangdd98** [comment]
các bác share để upvote bằng cách thả Reactions với cmt đi, em check mình ở [Top 39 trong bảng xếp hạng icon](https://fontawesome.com/leaderboard/brands) rồi. Hy vọng top cao được add sớm chứ nhiều lúc code đoạn icon của zalo thấy cồng kềnh quá phải xuất svg xong gọi trong css

**Comment by vnsur** [comment]
Không biết khi nào mới được lên

**Comment by lpnix** [comment]
hope soon

**Comment by quangdd98** [comment]
> Không biết khi nào mới được lên

lên đc top 26 rồi bác ạ

**Comment by vnsur** [comment]
vẫn chưa biết cách tính thế nào, chắc thêm cả viewpage

**Comment by quangdd98** [comment]
em tạo từ 2023 tới giờ là đc hơn 1 năm rồi vẫn chưa thấy gì

**Comment by vnsur** [comment]
vậy chắc khó, nhiều request tận 2016 vẫn chưa được

**Comment by quangdd98** [comment]
bài request từ 2016 nó gộp vào bài của em rồi bác ạ, tại hồi đấy đăng không đủ thông tin nên nó gộp vào topic của em :D

**Comment by duongnguyenrt** [comment]
Please make a zalo icon. All of vietnamese dev need it

**Comment by tawerg** [comment]
We are getting many requests for Zalo to be added as an icon to Font Awesome.  We would appreciate it if the team could add it soon :)

**Comment by han-phan-med** [comment]
Agree to add the Zalo icons

**Comment by LuongXuanNhat** [comment]
I really need it: Haizz

**Comment by Haiphamsg** [comment]
we need it plz

**Comment by quangdd98** [comment]
zalo đã lên [top 8 ](https://fontawesome.com/leaderboard/brands) rồi mọi người ạ, mọi người share để thêm người thả react, commend để đẩy top nhé

**Comment by vnsur** [comment]
thả react từng cmt à lên top nhé

**Comment by phong-pv** [comment]
please add it soon

**Comment by clinton67** [comment]
please add it!

**Comment by anasigu** [comment]
Pleaseeeeeeeeeeeeeeeeeeeeeeeeeeee!

**Comment by ghost** [comment]
Wait for more than 10 years for the icon 😵‍💫

**Comment by vnsur** [comment]
hiện tại là [top 7](https://fontawesome.com/leaderboard/brands) rồi, thả react nhiều vào

**Comment by giantpenguin** [comment]
please help to include these Zalo icons.

**Comment by duyplus** [comment]
upvote

**Comment by trevor-media** [comment]
Top 3 rồi mọi người ơi

https://fontawesome.com/leaderboard/brands

**Comment by quangdd98** [comment]
Request từ 2023 tới giờ mới leo lên được top 3 🥲🥲. Dù sao cũng sắp tới lượt icon zalo đc lên sàn rồi ae ạ

**Comment by sensibleworld** [comment]
So... our backlog of brand requests has reached a point where even we can't pretend we're keeping up. Some of these issues were opened before I had gray hair. And I've had gray hair for a LONG time. On top of that, treating requests as issues has always made it way too hard to see the forest for the trees.

To fix this, we are now managing all brand requests in **GitHub Discussions**. No more +1s or thumbs-ups needed. There's an upvote system built-in.

We are closing existing brand requests as part of this transition, but **we are not saying no** to your request.

**If this brand request is still relevant for you, please re-open it in Discussions** (and feel free to include a link back to this issue):
-> https://github.com/FortAwesome/Font-Awesome/discussions/new?category=brand-requests

And listen. We know this is annoying. If you need to vent, here are some pre-written responses you can use when opening the new discussion:

* Cool cool cool. No worry at all. I love re-requesting a brand that's redesigned three times while this issue was open.
* If an issue closes after seven years and nobody responds, did it ever really exist?
* I see you have chosen violence today. Re-opening per instructions.
* What's next? I have to file a TPS report, too?
* I am filled with the fury of a thousand suns. Why do I have to re-open the discussion? Couldn't you have just bulk converted all of the issues to discussions? What? You couldn't? What do you mean Github removed that feature earlier this year? You'd have to manually click the "convert to discussion" button on thousands of issues, while also ensuring it gets added to the correct category? That's a bunch of bull-phooey.
* No worries.
* This brand has gone the way of the dodo.

**Comment by piterlandy** [comment]
upvote

**Comment by LuongXuanNhat** [comment]
Bị chìm rồi, haizzz quả này 3 năm không có lun
