### ISSUE TITLE
Icon request: headphones slash

### ISSUE THREAD

**Issue by va1les** [FortAwesome/Font-Awesome#20217]
### Use case

For cases when you can't hear the person
![headphones-off](https://github.com/FortAwesome/Font-Awesome/assets/67857820/1c0c4479-8e1b-4e4d-9f07-260131ed7230)

### Example image

So that a person understands that he does not hear what others are saying

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)
```[tasklist]
### Tasks
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/224/

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader)

![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/d76b391d-ef59-4e4e-861b-edbb3f5348d7)

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
