### ISSUE TITLE
Icon request: 聯合國際海商業法庭+組織聯合國軍隊及改商全+敗家官12個人，敗家孫給敗家仔不好看。改變國際海旗，久的國際海旗設計改放去禁賭idea轉環保想法。are u forget... I say 紙都要做個股市。

### ISSUE THREAD

**Issue by PROGIDALjokersss** [FortAwesome/Font-Awesome#20408]
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

Welcome forlever welcome... 920111-08-5943wonghongyang ... Up list is me give we've... Idea

### Visual example

No enough for fuck9u... Late or lie what u want give me...? 
```[tasklist]
### Tasks
```
