### ISSUE TITLE
Miminal set of icons with add/remove overlay

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#5883]
Splitting out from #1181, which is about stacking **any** icon

**Please do not suggest css based solutions here**
- [ ] tag-plus, tag-times (#1384)
- [ ] file-plus, file-times, file-plus-o, file-times-o (#1525)
- [ ] folder-plus, folder-times, folder-plus-o, folder-times-o (#1525)
- [ ] shopping-cart-plus, shopping-cart-times (#473)
- [ ] fa-list-plus, fa-list-times (#4594)
- [ ] fa-bookmark-plus, fa-bookmark-times, fa-bookmark-plus-o, fa-bookmark-times-o (#5878)
- [ ] fa-database-plus, fa-database-times (#6072)

**Comment by AlainD-** [comment]
Hi I have a question: do you intent to create new icons ? For instance `folder-plus`. Will it be one new icon `fa-folder-plus` ?

If I understand correctly, your conclusion is to create a new set of icons. It seems so that you would like to create the whole icons directly. Which is great, and I think necessary (like the recent [`fa-user-plus`](http://fontawesome.io/icon/user-plus/) since v4.3.0).
But also, if so, then, it leaves us with few customization.

I was working since a couple of days on a prototype proposal to submit to your team. The idea is to create a set of smaller icons, referenced as badges, and used them with the stackings. So for instance, having a set of bottom badges, always put at the same position in the bottom right corner of a the svg canvas. That way, all the icons will be placed at the same place.

In order for you to understand, i published my prototype. Let me know what you think, and if we can go in that direction.
Here is the link on github: https://github.com/AlainD-/font-awesome-badge
Or directly to the demo page: http://alaind-.github.io/font-awesome-badge/


When I started the new set of icon badges, I had the customization matters in mind. For instance, if one would like to create a yellow folder plus this way: yellow folder with a green plus.
In fact we could imagine more combination such as: a yellow folder, with a green plus, inside a blue disk the whole surrounded by a red circle. It's ugly but anyway, it's just to demonstrate the variety of possibilities. Try this for instance in the [simulator on my page](http://alaind-.github.io/font-awesome-badge/#simulator):

```html
<span class="fa-stack fa-badge-stack fa-2x">
    <i class="fa fa-folder fa-stack-1x text-warning"></i>
    <i class="fa-badge fa-badge-bottom-circle-surround fa-stack-1x text-danger"></i>
    <i class="fa-badge fa-badge-bottom-circle fa-stack-1x text-success"></i>
    <i class="fa-badge fa-badge-bottom-plus fa-stack-1x text-info"></i>
</span>
```

Maybe we should consider both directions in order to meet a majority of user's expectations?

**Comment by tagliala** [comment]
> Hi I have a question: do you intent to create new icons ? For instance folder-plus. Will it be one new icon fa-folder-plus ?

Yes

> Maybe we should consider both directions in order to meet a majority of user's expectations?

And yes! As I said, I like that workaround. It comes with some drawbacks but does the job. We can keep discuss about it in #1181

**Comment by AlainD-** [comment]
HI, Is it possible to add the fa-database-* ?

**Comment by tagliala** [comment]
@AlainD- please open a new request and refer to this issue (and #1181)

**Comment by AlainD-** [comment]
Done #6072. But I don't see any option to attach new labels and reference to other issues (maybe because of user restriction).

**Comment by tagliala** [comment]
I'm going to close this because of the new SVG Framework
