### ISSUE TITLE
Icon Request: Chinese 12 symbolic animals

### ISSUE THREAD

**Issue by yarcowang** [FortAwesome/Font-Awesome#5927]
I'm not quite sure...I mean it is funny. For example, you could use dragon as icon font with your name, that is really cool.
But i don't know others like it or not...
(these symbolic animals represent a circle of years -- each for one year, so if you born then you tagged one animal -- mine is monkey)
```
Rat charm,子鼠 
Ox patient,丑牛 
Tiger sensitive,寅虎 
Rabbit articulate,卯兔 
Dragon healthy,辰龙 
Snake deep,巳蛇 
Horse popular,午马 
Goat elegant,未羊 
Monkey clever,申猴 
Rooster deep thinkers,酉鸡 
Dog loyalty,戌狗 
Pig chivalrous.亥猪
```

#957

**Comment by dngunraj** [comment]
+1

**Comment by Crissov** [comment]
Unicode has these as emojis and lists some local variants. For most of the animals, there are also (unified) facial variants.

1. 🐭 Rat 🐀 U+1F400 / Mouse 🐁 U+1F401/1F42D
2. 🐮 Ox 🐂 U+1F402 / Water Buffalo 🐃 U+1F403 / Cow 🐄 U+1F404/1F42E
3. 🐯 Tiger 🐅 U+1F405/1F42F / Leopard 🐆 U+1F406
4. 🐰 Rabbit 🐇 U+1F407/1F430 / 🐈 Cat U+1F408/1F431
5. 🐲 Dragon 🐉 U+1F409/1F432 / Snail 🐌 U+1F40C / 🐊 Crocodile U+1F40A / Whale 🐋🐳 U+1F40B/1F433
6. – Snake 🐍 U+1F40D
7. 🐴 Horse 🐎 U+1F40E/1F434 (Unicorn 🦄 U+1F984)
8. – Ram 🐏 U+1F40F / Goat 🐐 U+1F410 / Sheep 🐑 U+1F411
9. 🐵 Monkey 🐒 U+1F412/1F435 (Gorilla 🦍 U+1F98D)
10. 🐥 Rooster 🐓 U+1F413 / Chicken 🐔 U+1F414
11. 🐶 Dog 🐕 U+1F415/1F436 (Wolf 🐺 U+1F43A, Fox 🦊 U+1F98A)
12. 🐷 Pig 🐖 U+1F416/1F437 / Boar 🐗 U+1F417 / Elephant 🐘 U+1F418

These are the local variants mentioned in the Unicode Standard 9.0.

 * China:    🐀 🐂 🐅 🐇 🐉 🐍 🐎 🐏 🐒 🐓 🐕 🐖
 * Japan:   🐀 🐂 🐅 🐇 🐉 🐍 🐎 🐏 🐒 🐓 🐕 🐗
 * Thai:       🐀 🐂 🐅 🐇 🐉 🐍 🐎 🐏 🐒 🐓 🐕 🐘
 * Kazakh:     🐀 🐂 🐅 🐇 🐌 🐍 🐎 🐏 🐒 🐓 🐕 🐖
 * Vietnam: 🐀 🐃 🐅 🐈 🐉 🐍 🐎 🐐 🐒 🐓 🐕 🐖
 * Persian:    🐁 🐄 🐆 🐇 🐊/🐋 🐍 🐎 🐑 🐒 🐔 🐕 🐖

Two of these animals can be reused for the Western zodiac

1. ♈️ Aries 🐏 Ram
2. ♉️ Taurus 🐂 Ox
3. ♊️ Gemini 👬 Twins
4. ♋️ Cancer 🦀 Crab
5. ♌️ Leo 🦁 Lion
6. ♍️ Virgo 👧 Girl
7. ♎️ Libra ⚖ Scales
8. ♏️ Scorpius 🦂 Scorpion
9. ♐️ Sagittarius 🏹 Bow and Arrow
10. ♑️ Capricorn 🐐 (Sea) Goat or Ibex
11. ♒️ Aquarius 🏺 Amphora
12. ♓️ Pisces 🐟 (2) Fish

Snake (“serpent”) 🐍 can be used for the 13th constellation, Ophiucus ⛎.

**Comment by Crissov** [comment]
Font Awesome 5 has some new [animals](https://fontawesome.com/icons?d=gallery&c=animals), but some are still missing for this issue to be closed.

- [ ] Mouse
  - [ ] Rat
- [x] #4166 [Cow](https://fontawesome.com/icons/cow)
  - [ ] #1122 Ox
  - [ ] #1122 Water Buffalo
- [ ] #8413 Tiger
  - [ ] #8594 Leopard / Big Cat
- [x] #2453 [Rabbit](https://fontawesome.com/icons/rabbit), also [fast](https://fontawesome.com/icons/rabbit-fast)
  - [x] #2226 [Cat](https://fontawesome.com/icons/cat)
- [x] #2163 [Dragon](https://fontawesome.com/icons/dragon)
  - [ ] Crocodile
  - [ ] #8559 Snail
  - [x] [Whale](https://fontawesome.com/icons/whale) (also [Narwhal](https://fontawesome.com/icons/narwhal))
  - [ ] Seahorse
- [x] #3016 [Snake](https://fontawesome.com/icons/snake)
- [x] #2049 [Horse](https://fontawesome.com/icons/horse)
  - #2780 [Unicorn](https://fontawesome.com/icons/unicorn) (also [Alicorn](https://fontawesome.com/icons/alicorn) and [Pegasus](https://fontawesome.com/icons/pegasus))
- [x] #6909 [Sheep](https://fontawesome.com/icons/sheep) 
  - [x]  [Ram](https://fontawesome.com/icons/ram)
  - [ ] Goat
- [x] #4158 [Monkey](https://fontawesome.com/icons/monkey)
  - #8593 Gorilla
- [ ] Chicken (but [Duck](https://fontawesome.com/icons/duck))
  - [ ] Rooster
  - [ ] Chick (but [Kiwi](https://fontawesome.com/icons/kiwi-bird))
- [x] #1317 [Dog](https://fontawesome.com/icons/dog), also [leashed](https://fontawesome.com/icons/dog-leashed)
  - Wolf
  - Fox
- [x] [Pig](https://fontawesome.com/icons/pig)
  - [ ] Boar
  - [x] #8592 [Elephant](https://fontawesome.com/icons/elephant)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’ve added this issue to our new list to be created! We can’t promise any firm timelines right now, but this will help us keep track of it.

We’ll update this issue when the icon is released into the wild 🙂

**Comment by sensibleworld** [comment]
Hey there!

We've made the decision to move our icon requests flow to **GitHub Discussions**, as opposed to issue tracking. No more +1s or thumbs-ups needed. There's an upvote system built in.

As part of this transition, we are closing existing icon requests with lower comment or reaction counts, but **we are not saying no** to your request. (We know some of these have been open since before I had gray hair. And I've had gray hair for a LONG time.)

**Could you do us a favor? If this icon request is still relevant for you, please re-open it in Discussions** (and feel free to include a link back to this issue):
→ https://github.com/FortAwesome/Font-Awesome/discussions/new?category=icon-requests

And listen. We know this is annoying. We would batch convert them to discussions if we could, but Github's removed that ability earlier this year. If you need to vent, here are some pre-written responses you can use when opening the new discussion:

* Cool cool cool. No worries at all. I love doing things twice.
* If an issue closes after seven years and nobody responds, did it ever really exist?
* I see you have chosen violence today. Re-opening per instructions.
* What's next? I have to file a TPS report, too?
* I am filled with the fury of a thousand suns. This request already HAS an auto-response saying that you're refining the workflow. What do you mean you're refining your refinement? That's a bunch of bull-phooey.
* No biggie. Thanks for letting us know what's up.
