### ISSUE TITLE
New Icon Category: Accessibility

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#8895]
Existing FA icons to add to accessibility category:
- [x] fa-tty
- [x] fa-wheelchair
- [x] fa-cc (closed-captioning)
- [x] fa-question
- [x] fa-question-circle

New icons to add with proposed names (from https://www.graphicartistsguild.org/tools_resources/downloadable-disability-access-symbols):
- [x] fa-universal-access (#614)
- [x] fa-wheelchair-alt (#2746) - anyone have suggestions for a better name for this one?
- [x] fa-blind
- [x] fa-audio-description (#3176)
- [x] fa-volume-control-telephone
- [x] fa-assistive-listening-systems (#5409)
- [x] fa-american-sign-language-interpreting (alias fa-asl-interpreting) (#2026)
- [x] fa-question-circle-o (#5972)
- [x] fa-braille (#5753)
- [x] fa-deaf (aliases fa-deafness, fa-hard-of-hearing) (#5409)
- [x] fa-sign-language (#2026)
- [x] fa-low-vision

**Comment by tagliala** [comment]
Sign language interpretation = #2026 ?

**Comment by davegandy** [comment]
@tagliala Updated.

**Comment by nfreear** [comment]
👍  for the new category & included icons. Thank you!

Nick

**Comment by tagliala** [comment]
added #5972 question-circle-o

**Comment by tagliala** [comment]
added #3176 audio description (the request is about two icons, but probably the second one is #8349)

**Comment by davegandy** [comment]
@tagliala Man, thank you. Very very very helpful.

**Comment by caduvieira** [comment]
How about fa-wheelchair-active or fa-wheelchair-moving

**Comment by davegandy** [comment]
@caduvieira How about #2746?

**Comment by davegandy** [comment]
All icons have been added to 4.6.0-wip branch. Closing.

**Comment by truls1502** [comment]
Hello,

I just want to have your confirm about the sign language icon:

I see you have added "fa-american-sign-language", but it will be only focusing on American Sign Language. It is great, but I am not sure which icon you will use in 4.6.0 version. If you are thinking to use this image on the first post on the thread on https://github.com/FortAwesome/Font-Awesome/issues/2026#issue-20022685 then this sign means "interpreter" in American Sign Language. So if you are adding this icon, I would recommend you to change from "fa-american-sign-language" to something like "fa-american-signlanguage-interpreter" or shortly "fa-asl-interpreter". Because each country have different sign for interpreter.

So I really appreciate if you could add the "universal sign" for the Sign Language which is more alike to this icon on the post https://github.com/FortAwesome/Font-Awesome/issues/2026#issuecomment-102100667

Thank you in advance :)

**Comment by tagliala** [comment]
@truls1502 is it just an aesthetic question?

**Comment by tagliala** [comment]
@davegandy reopened here, removed #5409 reference in the todo-list

I did not add a reference to

- [_] Hard of earing (#5409)

**Comment by truls1502** [comment]
@tagliala it is two different things ASL (American Sign Language) and Sign Language Interpreters. I just want to make it more clearly and not confuse anyone, especially when hearing is programming website for deaf and doesn't know deaf culture.

**Comment by davegandy** [comment]
@truls1502 Excellent feedback. Here's a preview of the icon:
<img width="986" alt="screenshot 2016-04-07 09 18 01" src="https://cloud.githubusercontent.com/assets/1076721/14354239/2887cc5c-fca2-11e5-9b29-ac117a342388.png">

I'll rename to sign-language-interpreting. It's a solid start for now and we can add more international symbols as we go. Do you have a resource where I can learn about the nuances between the symbols we'll eventually want to add?

**Comment by davegandy** [comment]
Added separate low vision icon to 4.6.0-wip branch. Closing.

<img width="794" alt="screenshot 2016-04-07 17 41 03" src="https://cloud.githubusercontent.com/assets/1076721/14369113/ee7b5f56-fce7-11e5-90be-a6d14620d964.png">
